export const AI_ACT_CORPUS = [
  {
    "code": "R-Art-5",
    "article_no": "5",
    "title": "Prohibited AI practices",
    "snippet": "AI practices including subliminal manipulation, exploiting vulnerabilities, social scoring leading to detrimental treatment, and emotion recognition in the workplace or education are prohibited.",
    "full_text": "Article 5 — Prohibited AI practices. The placing on the market, the putting into service or the use of AI systems that deploy subliminal techniques beyond a person's consciousness, exploit any vulnerabilities of a specific group, evaluate or classify natural persons or groups based on social behaviour (social scoring) leading to detrimental or unfavourable treatment, or infer emotions of a natural person in the areas of workplace and education institutions, are prohibited.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-6",
    "article_no": "6",
    "title": "Classification rules for high-risk AI systems",
    "snippet": "An AI system shall be considered high-risk where it is listed in Annex III or used as a safety component of a product covered by Annex I.",
    "full_text": "Article 6 — Classification rules for high-risk AI systems. An AI system shall be considered to be high-risk where (a) it is intended to be used as a safety component of a product, or it is itself a product, covered by Union harmonisation legislation listed in Annex I, and (b) it is required to undergo a third-party conformity assessment. AI systems referred to in Annex III shall also be considered high-risk. Article 6(3) lists narrow exemptions where a high-risk-listed system is not considered high-risk in practice.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-9",
    "article_no": "9",
    "title": "Risk management system",
    "snippet": "Providers of high-risk AI systems shall establish, implement, document and maintain a risk management system across the AI lifecycle.",
    "full_text": "Article 9 — Risk management system. A risk management system shall be established, implemented, documented and maintained in relation to high-risk AI systems. It shall consist of a continuous iterative process planned and run throughout the entire lifecycle of the AI system, requiring regular systematic review and updating, including identification and analysis of foreseeable risks and adoption of appropriate risk-management measures.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-12",
    "article_no": "12",
    "title": "Record-keeping (lifecycle logging)",
    "snippet": "High-risk AI systems shall technically allow for the automatic recording of events (logs) over the duration of the system's lifetime.",
    "full_text": "Article 12 — Record-keeping. High-risk AI systems shall be designed and developed with capabilities enabling the automatic recording of events (logs) over their lifetime. Logging capabilities shall enable the identification of risks, the monitoring of operation, and post-market monitoring. Logs shall be retained for at least six months by deployers.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-13",
    "article_no": "13",
    "title": "Transparency and provision of information to deployers",
    "snippet": "High-risk AI systems shall be designed so deployers can interpret the system's output and use it appropriately, including via comprehensible instructions for use.",
    "full_text": "Article 13 — Transparency and provision of information to deployers. High-risk AI systems shall be designed and developed in such a way that their operation is sufficiently transparent to enable deployers to interpret the system's output and use it appropriately. They shall be accompanied by instructions for use providing information that is concise, complete, correct and clear.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-14",
    "article_no": "14",
    "title": "Human oversight",
    "snippet": "High-risk AI systems shall be designed and developed so they can be effectively overseen by natural persons during the period in which they are in use.",
    "full_text": "Article 14 — Human oversight. High-risk AI systems shall be designed and developed in such a way, including with appropriate human-machine interface tools, that they can be effectively overseen by natural persons during the period in which they are in use. Oversight measures shall be commensurate with the risks, the level of autonomy and the context of use. Natural persons assigned oversight shall be able to understand the capacities and limitations of the system, monitor for anomalies, and intervene or interrupt the system through a 'stop' button.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-17",
    "article_no": "17",
    "title": "Quality management system (QMS)",
    "snippet": "Providers of high-risk AI systems shall put a documented quality management system in place ensuring compliance with the Regulation.",
    "full_text": "Article 17 — Quality management system. Providers of high-risk AI systems shall put a quality management system in place that ensures compliance with this Regulation. That system shall be documented in a systematic and orderly manner in the form of written policies, procedures and instructions, and shall include strategies for regulatory compliance, techniques for the design, development and quality control of the system, and resource management.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-27",
    "article_no": "27",
    "title": "Fundamental rights impact assessment (FRIA)",
    "snippet": "Deployers of certain high-risk AI systems shall perform an assessment of the impact on fundamental rights that the use of the system may produce.",
    "full_text": "Article 27 — Fundamental rights impact assessment for high-risk AI systems. Prior to deploying a high-risk AI system referred to in Article 6(2), with the exception of systems intended for use in critical infrastructure, deployers that are bodies governed by public law or private entities providing public services, and deployers of credit-scoring or insurance-pricing AI, shall perform an assessment of the impact on fundamental rights that the use of such a system may produce. The deployer shall notify the market surveillance authority of the results.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-50",
    "article_no": "50",
    "title": "Transparency obligations for certain AI systems",
    "snippet": "Providers and deployers of AI systems intended to interact directly with natural persons, or that generate synthetic content, shall ensure that users are informed.",
    "full_text": "Article 50 — Transparency obligations for providers and deployers of certain AI systems. Providers shall ensure that AI systems intended to interact directly with natural persons are designed and developed in such a way that the natural persons concerned are informed that they are interacting with an AI system. Providers of AI systems generating synthetic audio, image, video or text content shall ensure that the outputs are marked as artificially generated or manipulated. Deployers of deep-fake content shall disclose that the content has been artificially generated or manipulated.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-51",
    "article_no": "51",
    "title": "Classification of GPAI models",
    "snippet": "A general-purpose AI model shall be classified as having systemic risk if it has high-impact capabilities.",
    "full_text": "Article 51 — Classification of general-purpose AI models as GPAI with systemic risk. A general-purpose AI model is classified as having systemic risk if it has high-impact capabilities evaluated on the basis of appropriate technical tools and methodologies, including indicators and benchmarks, or if so designated by the Commission ex officio or following a qualified alert from the scientific panel.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-53",
    "article_no": "53",
    "title": "Obligations for providers of GPAI models",
    "snippet": "Providers of GPAI models shall draw up and keep up-to-date technical documentation of the model and make information available to downstream providers.",
    "full_text": "Article 53 — Obligations for providers of general-purpose AI models. Providers shall draw up and keep up to date technical documentation, including training and testing process and the results of evaluation; draw up and keep up to date information for downstream providers; put in place a policy to respect Union copyright law; and publish a sufficiently detailed summary of the training content.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-55",
    "article_no": "55",
    "title": "Obligations for providers of GPAI models with systemic risk",
    "snippet": "Providers of GPAI models with systemic risk shall perform model evaluation, assess and mitigate systemic risks, and report serious incidents.",
    "full_text": "Article 55 — Obligations for providers of general-purpose AI models with systemic risk. In addition to obligations under Article 53, providers shall perform model evaluation including adversarial testing, assess and mitigate possible systemic risks at Union level, keep track of and report serious incidents to the AI Office, and ensure an adequate level of cybersecurity protection.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-71",
    "article_no": "71",
    "title": "EU database for high-risk AI systems",
    "snippet": "The Commission shall set up and maintain an EU database for high-risk AI systems referred to in Annex III; providers shall register their systems.",
    "full_text": "Article 71 — EU database for high-risk AI systems listed in Annex III. The Commission shall, in collaboration with the Member States, set up and maintain a database containing information on high-risk AI systems. Providers and, where applicable, deployers that are public authorities, shall enter and update the relevant information set out in Annex VIII.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-1",
    "article_no": "Annex-III-1",
    "title": "Annex III §1 — Biometrics",
    "snippet": "AI systems intended for remote biometric identification, biometric categorisation, or emotion recognition are considered high-risk.",
    "full_text": "Annex III §1 — Biometrics. The following biometric AI systems are considered high-risk: (a) remote biometric identification systems, excluding verification confirming a specific person is the person they claim to be; (b) AI systems for biometric categorisation according to sensitive or protected attributes; (c) AI systems intended for emotion recognition outside the prohibited contexts of Article 5.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-2",
    "article_no": "Annex-III-2",
    "title": "Annex III §2 — Critical infrastructure",
    "snippet": "AI systems intended for use as safety components in the management and operation of critical digital infrastructure, road traffic, or the supply of water, gas, heating, and electricity are high-risk.",
    "full_text": "Annex III §2 — Critical infrastructure. AI systems intended to be used as safety components in the management and operation of critical digital infrastructure, road traffic, or in the supply of water, gas, heating and electricity. Failure of such systems can endanger the life and health of persons at large scale and disrupt the ordinary conduct of social and economic activities.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-3",
    "article_no": "Annex-III-3",
    "title": "Annex III §3 — Education and vocational training",
    "snippet": "AI systems determining access to, admission to, or assignment within educational institutions, or evaluating learning outcomes, are high-risk.",
    "full_text": "Annex III §3 — Education and vocational training. AI systems intended to be used: (a) to determine access or admission to educational and vocational training institutions or to assign natural persons to them; (b) to evaluate learning outcomes; (c) to assess the appropriate level of education for an individual; (d) to monitor and detect prohibited behaviour during tests.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-4",
    "article_no": "Annex-III-4",
    "title": "Annex III §4 — Employment, workers management and access to self-employment",
    "snippet": "AI systems for recruitment or selection of natural persons — in particular advertising, filtering applications and evaluating candidates — are high-risk.",
    "full_text": "Annex III §4 — Employment, workers management and access to self-employment. AI systems intended to be used: (a) for the recruitment or selection of natural persons, in particular to place targeted job advertisements, to analyse and filter job applications, and to evaluate candidates; (b) to make decisions affecting terms of work-related relationships, the promotion or termination of work-related contractual relationships, to allocate tasks based on individual behaviour or personal traits or characteristics, or to monitor and evaluate the performance and behaviour of persons.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-5",
    "article_no": "Annex-III-5",
    "title": "Annex III §5 — Essential private and public services",
    "snippet": "AI systems used to evaluate eligibility for essential services or benefits, including credit-worthiness of natural persons, are high-risk.",
    "full_text": "Annex III §5 — Access to and enjoyment of essential private services and essential public services and benefits. AI systems intended to be used: (a) by public authorities to evaluate the eligibility of natural persons for benefits and services; (b) to evaluate the creditworthiness of natural persons or establish credit scores, with the exception of AI used for the purpose of detecting financial fraud; (c) for risk assessment and pricing in life and health insurance; (d) to evaluate and classify emergency calls or to dispatch emergency services.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-6",
    "article_no": "Annex-III-6",
    "title": "Annex III §6 — Law enforcement",
    "snippet": "AI systems intended to be used by law enforcement authorities for risk profiling, evidence evaluation, polygraphs, or crime analytics are high-risk.",
    "full_text": "Annex III §6 — Law enforcement. AI systems intended to be used by, or on behalf of, law enforcement authorities, or by Union institutions, bodies, offices, or agencies in support of law enforcement, for: (a) assessing the risk of a natural person becoming the victim of criminal offences; (b) polygraphs and similar tools; (c) evaluating the reliability of evidence; (d) profiling natural persons in the course of detection, investigation, or prosecution of criminal offences; (e) crime analytics.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-7",
    "article_no": "Annex-III-7",
    "title": "Annex III §7 — Migration, asylum, and border control",
    "snippet": "AI systems used by competent authorities for migration, asylum, or border-control management — including risk assessments and document verification — are high-risk.",
    "full_text": "Annex III §7 — Migration, asylum, and border control management. AI systems intended to be used by competent public authorities, or by Union institutions, bodies, offices, or agencies, for: (a) polygraphs and similar tools; (b) assessing security, irregular-migration, or health risks posed by a natural person who intends to enter the Union; (c) examining applications for asylum, visas, and residence permits and associated complaints; (d) detecting, recognising, or identifying natural persons in border-management contexts.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Annex-III-8",
    "article_no": "Annex-III-8",
    "title": "Annex III §8 — Administration of justice and democratic processes",
    "snippet": "AI systems assisting judicial authorities in researching or interpreting facts and law, or used to influence elections or voting behaviour, are high-risk.",
    "full_text": "Annex III §8 — Administration of justice and democratic processes. AI systems intended to be used: (a) by a judicial authority, or on its behalf, to assist in researching and interpreting facts and the law and in applying the law to a concrete set of facts, or in alternative dispute resolution; (b) to influence the outcome of an election or referendum or the voting behaviour of natural persons, with the exception of outputs whose addressee is not directly exposed to the system (such as back-office logistical tools).",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Recital-31",
    "article_no": "Recital-31",
    "title": "Recital 31 — Social scoring concerns",
    "snippet": "AI systems providing social scoring of natural persons can lead to discriminatory outcomes and exclusion.",
    "full_text": "Recital 31 — AI systems providing social scoring of natural persons by public or private actors may lead to discriminatory outcomes and the exclusion of certain groups. They may violate the right to dignity and non-discrimination and values of equality and justice. Such systems are therefore prohibited under Article 5.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Recital-44",
    "article_no": "Recital-44",
    "title": "Recital 44 — Emotion recognition risks",
    "snippet": "Emotion-recognition AI in workplace and education raises serious concerns about scientific basis, bias, and intrusion.",
    "full_text": "Recital 44 — Serious concerns exist about the scientific basis of AI systems aimed at identifying or inferring emotions, particularly in the workplace and in education, where there is a power imbalance. Such systems can lead to detrimental or unfavourable treatment and are prohibited in those contexts.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Recital-53",
    "article_no": "Recital-53",
    "title": "Recital 53 — Minimal-risk systems",
    "snippet": "The vast majority of AI systems currently used pose minimal or no risk and may contribute to important benefits.",
    "full_text": "Recital 53 — The vast majority of AI systems currently used in the Union pose minimal or no risk and may contribute to important societal and economic benefits. They are not subject to specific obligations under this Regulation, but providers and deployers are encouraged to apply voluntary codes of conduct.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Recital-71",
    "article_no": "Recital-71",
    "title": "Recital 71 — High-risk classification rationale",
    "snippet": "AI systems should be classified as high-risk only when they pose significant risk of harm to fundamental rights, health, or safety.",
    "full_text": "Recital 71 — AI systems should be classified as high-risk only when they pose a significant risk of harm to the health, safety or fundamental rights of natural persons, taking into account the severity of the possible harm and its probability of occurrence.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Recital-132",
    "article_no": "Recital-132",
    "title": "Recital 132 — Transparency for AI interactions",
    "snippet": "Natural persons should be informed when they are interacting with an AI system, unless this is obvious from the circumstances.",
    "full_text": "Recital 132 — Natural persons should be informed when they are interacting with an AI system, unless that is obvious from the circumstances and the context of use. The obligation to inform should be considered fulfilled when the AI system is clearly identifiable as such, taking into account the perception of an averagely well-informed and observant person.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Recital-134",
    "article_no": "Recital-134",
    "title": "Recital 134 — Synthetic content disclosure",
    "snippet": "Providers of generative AI should mark outputs in a machine-readable format detectable as artificially generated.",
    "full_text": "Recital 134 — Providers of AI systems generating synthetic audio, image, video or text should ensure that outputs are marked in a machine-readable format and detectable as artificially generated or manipulated. Technical solutions should be effective, interoperable, robust and reliable, taking into account the state of the art.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Guide-prohibited-001",
    "article_no": "Guide-prohibited-001",
    "title": "Commission guidance on prohibited AI practices",
    "snippet": "Guidance clarifying scope of Article 5 prohibitions, including the workplace emotion-recognition prohibition.",
    "full_text": "Commission guidance on prohibited AI practices (Article 5). The guidance clarifies that emotion-recognition systems used in the workplace fall under the prohibition irrespective of whether they are used by the employer or by a third party on the employer's behalf. Medical and safety-related uses are out of scope of the prohibition.",
    "source_type": "guidance",
    "source_label": "European Commission, AI Office",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-FI-traficom-001",
    "article_no": "FI-Traficom-001",
    "title": "Finnish national competent authority (Traficom)",
    "snippet": "Traficom is the designated Finnish notifying authority and market surveillance authority under the AI Act.",
    "full_text": "Finland has designated Liikenne- ja viestintävirasto (Traficom) as the national notifying authority and market surveillance authority for the AI Act. Deployers and providers established in Finland should direct incident reports, FRIA notifications, and registration queries to Traficom's AI Office unit.",
    "source_type": "national",
    "source_label": "Traficom (Finland)",
    "url": null,
    "relevance_score": null
  },
  {
    "code": "R-Art-1",
    "article_no": "1",
    "title": "Subject matter",
    "snippet": "1.   The purpose of this Regulation is to improve the functioning of the internal market and promote the uptake of human-centric and trustworthy artificial intelligence (AI), while ensuring a high…",
    "full_text": "1.   The purpose of this Regulation is to improve the functioning of the internal market and promote the uptake of human-centric and trustworthy artificial intelligence (AI), while ensuring a high level of protection of health, safety, fundamental rights enshrined in the Charter, including democracy, the rule of law and environmental protection, against the harmful effects of AI systems in the Union and supporting innovation. 2.   This Regulation lays down: (a) harmonised rules for the placing on the market, the putting into service, and the use of AI systems in the Union; (b) prohibitions of certain AI practices; (c) specific requirements for high-risk AI systems and obligations for operators of such systems; (d) harmonised transparency rules for certain AI systems; (e) harmonised rules for the placing on the market of general-purpose AI models; (f) rules on market monitoring, market surveillance, governance and enforcement; (g) measures to support innovation, with a particular focus on SMEs, including start-ups.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-2",
    "article_no": "2",
    "title": "Scope",
    "snippet": "1.   This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those…",
    "full_text": "1.   This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those providers are established or located within the Union or in a third country; (b) deployers of AI systems that have their place of establishment or are located within the Union; (c) providers and deployers of AI systems that have their place of establishment or are located in a third country, where the output produced by the AI system is used in the Union; (d) importers and distributors of AI systems; (e) product manufacturers placing on the market or putting into service an AI system together with their product and under their own name or trademark; (f) authorised representatives of providers, which are not established in the Union; (g) affected persons that are located in the Union. 2.   For AI systems classified as high-risk AI systems in accordance with Article 6(1) related to products covered by the Union harmonisation legislation listed in Section B of Annex I, only Article 6(1), Articles 102 to 109 and Article 112 apply. Article 57 applies only in so far as the requirements for high-risk AI systems under this Regulation have been integrated in that Union harmonisation legislation. 3.   This Regulation does not apply to areas outside the scope of Union law, and shall not, in any event, affect the competences of the Member States concerning national security, regardless of…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-3",
    "article_no": "3",
    "title": "Definitions",
    "snippet": "For the purposes of this Regulation, the following definitions apply: (1) ‘AI system’ means a machine-based system that is designed to operate with varying levels of autonomy and that may exhibit…",
    "full_text": "For the purposes of this Regulation, the following definitions apply: (1) ‘AI system’ means a machine-based system that is designed to operate with varying levels of autonomy and that may exhibit adaptiveness after deployment, and that, for explicit or implicit objectives, infers, from the input it receives, how to generate outputs such as predictions, content, recommendations, or decisions that can influence physical or virtual environments; (2) ‘risk’ means the combination of the probability of an occurrence of harm and the severity of that harm; (3) ‘provider’ means a natural or legal person, public authority, agency or other body that develops an AI system or a general-purpose AI model or that has an AI system or a general-purpose AI model developed and places it on the market or puts the AI system into service under its own name or trademark, whether for payment or free of charge; (4) ‘deployer’ means a natural or legal person, public authority, agency or other body using an AI system under its authority except where the AI system is used in the course of a personal non-professional activity; (5) ‘authorised representative’ means a natural or legal person located or established in the Union who has received and accepted a written mandate from a provider of an AI system or a general-purpose AI model to, respectively, perform and carry out on its behalf the obligations and procedures established by this Regulation; (6) ‘importer’ means a natural or legal person located or…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-4",
    "article_no": "4",
    "title": "AI literacy",
    "snippet": "Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI…",
    "full_text": "Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, experience, education and training and the context the AI systems are to be used in, and considering the persons or groups of persons on whom the AI systems are to be used.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-7",
    "article_no": "7",
    "title": "Amendments to Annex III",
    "snippet": "1.   The Commission is empowered to adopt delegated acts in accordance with Article 97 to amend Annex III by adding or modifying use-cases of high-risk AI systems where both of the following…",
    "full_text": "1.   The Commission is empowered to adopt delegated acts in accordance with Article 97 to amend Annex III by adding or modifying use-cases of high-risk AI systems where both of the following conditions are fulfilled: (a) the AI systems are intended to be used in any of the areas listed in Annex III; (b) the AI systems pose a risk of harm to health and safety, or an adverse impact on fundamental rights, and that risk is equivalent to, or greater than, the risk of harm or of adverse impact posed by the high-risk AI systems already referred to in Annex III. 2.   When assessing the condition under paragraph 1, point (b), the Commission shall take into account the following criteria: (a) the intended purpose of the AI system; (b) the extent to which an AI system has been used or is likely to be used; (c) the nature and amount of the data processed and used by the AI system, in particular whether special categories of personal data are processed; (d) the extent to which the AI system acts autonomously and the possibility for a human to override a decision or recommendations that may lead to potential harm; (e) the extent to which the use of an AI system has already caused harm to health and safety, has had an adverse impact on fundamental rights or has given rise to significant concerns in relation to the likelihood of such harm or adverse impact, as demonstrated, for example, by reports or documented allegations submitted to national competent authorities or by other reports, as…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-8",
    "article_no": "8",
    "title": "Compliance with the requirements",
    "snippet": "1.   High-risk AI systems shall comply with the requirements laid down in this Section, taking into account their intended purpose as well as the generally acknowledged state of the art on AI and…",
    "full_text": "1.   High-risk AI systems shall comply with the requirements laid down in this Section, taking into account their intended purpose as well as the generally acknowledged state of the art on AI and AI-related technologies. The risk management system referred to in Article 9 shall be taken into account when ensuring compliance with those requirements. 2.   Where a product contains an AI system, to which the requirements of this Regulation as well as requirements of the Union harmonisation legislation listed in Section A of Annex I apply, providers shall be responsible for ensuring that their product is fully compliant with all applicable requirements under applicable Union harmonisation legislation. In ensuring the compliance of high-risk AI systems referred to in paragraph 1 with the requirements set out in this Section, and in order to ensure consistency, avoid duplication and minimise additional burdens, providers shall have a choice of integrating, as appropriate, the necessary testing and reporting processes, information and documentation they provide with regard to their product into documentation and procedures that already exist and are required under the Union harmonisation legislation listed in Section A of Annex I.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-10",
    "article_no": "10",
    "title": "Data and data governance",
    "snippet": "1.   High-risk AI systems which make use of techniques involving the training of AI models with data shall be developed on the basis of training, validation and testing data sets that meet the…",
    "full_text": "1.   High-risk AI systems which make use of techniques involving the training of AI models with data shall be developed on the basis of training, validation and testing data sets that meet the quality criteria referred to in paragraphs 2 to 5 whenever such data sets are used. 2.   Training, validation and testing data sets shall be subject to data governance and management practices appropriate for the intended purpose of the high-risk AI system. Those practices shall concern in particular: (a) the relevant design choices; (b) data collection processes and the origin of data, and in the case of personal data, the original purpose of the data collection; (c) relevant data-preparation processing operations, such as annotation, labelling, cleaning, updating, enrichment and aggregation; (d) the formulation of assumptions, in particular with respect to the information that the data are supposed to measure and represent; (e) an assessment of the availability, quantity and suitability of the data sets that are needed; (f) examination in view of possible biases that are likely to affect the health and safety of persons, have a negative impact on fundamental rights or lead to discrimination prohibited under Union law, especially where data outputs influence inputs for future operations; (g) appropriate measures to detect, prevent and mitigate possible biases identified according to point (f); (h) the identification of relevant data gaps or shortcomings that prevent compliance with…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-11",
    "article_no": "11",
    "title": "Technical documentation",
    "snippet": "1.   The technical documentation of a high-risk AI system shall be drawn up before that system is placed on the market or put into service and shall be kept up-to date. The technical documentation…",
    "full_text": "1.   The technical documentation of a high-risk AI system shall be drawn up before that system is placed on the market or put into service and shall be kept up-to date. The technical documentation shall be drawn up in such a way as to demonstrate that the high-risk AI system complies with the requirements set out in this Section and to provide national competent authorities and notified bodies with the necessary information in a clear and comprehensive form to assess the compliance of the AI system with those requirements. It shall contain, at a minimum, the elements set out in Annex IV. SMEs, including start-ups, may provide the elements of the technical documentation specified in Annex IV in a simplified manner. To that end, the Commission shall establish a simplified technical documentation form targeted at the needs of small and microenterprises. Where an SME, including a start-up, opts to provide the information required in Annex IV in a simplified manner, it shall use the form referred to in this paragraph. Notified bodies shall accept the form for the purposes of the conformity assessment. 2.   Where a high-risk AI system related to a product covered by the Union harmonisation legislation listed in Section A of Annex I is placed on the market or put into service, a single set of technical documentation shall be drawn up containing all the information set out in paragraph 1, as well as the information required under those legal acts. 3.   The Commission is empowered to…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-15",
    "article_no": "15",
    "title": "Accuracy, robustness and cybersecurity",
    "snippet": "1.   High-risk AI systems shall be designed and developed in such a way that they achieve an appropriate level of accuracy, robustness, and cybersecurity, and that they perform consistently in those…",
    "full_text": "1.   High-risk AI systems shall be designed and developed in such a way that they achieve an appropriate level of accuracy, robustness, and cybersecurity, and that they perform consistently in those respects throughout their lifecycle. 2.   To address the technical aspects of how to measure the appropriate levels of accuracy and robustness set out in paragraph 1 and any other relevant performance metrics, the Commission shall, in cooperation with relevant stakeholders and organisations such as metrology and benchmarking authorities, encourage, as appropriate, the development of benchmarks and measurement methodologies. 3.   The levels of accuracy and the relevant accuracy metrics of high-risk AI systems shall be declared in the accompanying instructions of use. 4.   High-risk AI systems shall be as resilient as possible regarding errors, faults or inconsistencies that may occur within the system or the environment in which the system operates, in particular due to their interaction with natural persons or other systems. Technical and organisational measures shall be taken in this regard. The robustness of high-risk AI systems may be achieved through technical redundancy solutions, which may include backup or fail-safe plans. High-risk AI systems that continue to learn after being placed on the market or put into service shall be developed in such a way as to eliminate or reduce as far as possible the risk of possibly biased outputs influencing input for future operations…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-16",
    "article_no": "16",
    "title": "Obligations of providers of high-risk AI systems",
    "snippet": "Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is…",
    "full_text": "Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, as applicable, their name, registered trade name or registered trade mark, the address at which they can be contacted; (c) have a quality management system in place which complies with Article 17; (d) keep the documentation referred to in Article 18; (e) when under their control, keep the logs automatically generated by their high-risk AI systems as referred to in Article 19; (f) ensure that the high-risk AI system undergoes the relevant conformity assessment procedure as referred to in Article 43, prior to its being placed on the market or put into service; (g) draw up an EU declaration of conformity in accordance with Article 47; (h) affix the CE marking to the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, to indicate conformity with this Regulation, in accordance with Article 48; (i) comply with the registration obligations referred to in Article 49(1); (j) take the necessary corrective actions and provide information as required in Article 20; (k) upon a reasoned request of a national competent authority, demonstrate the conformity of the high-risk AI system with the requirements set out in Section 2; (l) ensure that the high-risk AI system complies…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-18",
    "article_no": "18",
    "title": "Documentation keeping",
    "snippet": "1.   The provider shall, for a period ending 10 years after the high-risk AI system has been placed on the market or put into service, keep at the disposal of the national competent authorities: (a)…",
    "full_text": "1.   The provider shall, for a period ending 10 years after the high-risk AI system has been placed on the market or put into service, keep at the disposal of the national competent authorities: (a) the technical documentation referred to in Article 11; (b) the documentation concerning the quality management system referred to in Article 17; (c) the documentation concerning the changes approved by notified bodies, where applicable; (d) the decisions and other documents issued by the notified bodies, where applicable; (e) the EU declaration of conformity referred to in Article 47. 2.   Each Member State shall determine conditions under which the documentation referred to in paragraph 1 remains at the disposal of the national competent authorities for the period indicated in that paragraph for the cases when a provider or its authorised representative established on its territory goes bankrupt or ceases its activity prior to the end of that period. 3.   Providers that are financial institutions subject to requirements regarding their internal governance, arrangements or processes under Union financial services law shall maintain the technical documentation as part of the documentation kept under the relevant Union financial services law.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-22",
    "article_no": "22",
    "title": "Authorised representatives of providers of high-risk AI systems",
    "snippet": "1.   Prior to making their high-risk AI systems available on the Union market, providers established in third countries shall, by written mandate, appoint an authorised representative which is…",
    "full_text": "1.   Prior to making their high-risk AI systems available on the Union market, providers established in third countries shall, by written mandate, appoint an authorised representative which is established in the Union. 2.   The provider shall enable its authorised representative to perform the tasks specified in the mandate received from the provider. 3.   The authorised representative shall perform the tasks specified in the mandate received from the provider. It shall provide a copy of the mandate to the market surveillance authorities upon request, in one of the official languages of the institutions of the Union, as indicated by the competent authority. For the purposes of this Regulation, the mandate shall empower the authorised representative to carry out the following tasks: (a) verify that the EU declaration of conformity referred to in Article 47 and the technical documentation referred to in Article 11 have been drawn up and that an appropriate conformity assessment procedure has been carried out by the provider; (b) keep at the disposal of the competent authorities and national authorities or bodies referred to in Article 74(10), for a period of 10 years after the high-risk AI system has been placed on the market or put into service, the contact details of the provider that appointed the authorised representative, a copy of the EU declaration of conformity referred to in Article 47, the technical documentation and, if applicable, the certificate issued by the…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-25",
    "article_no": "25",
    "title": "Responsibilities along the AI value chain",
    "snippet": "1.   Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations…",
    "full_text": "1.   Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the following circumstances: (a) they put their name or trademark on a high-risk AI system already placed on the market or put into service, without prejudice to contractual arrangements stipulating that the obligations are otherwise allocated; (b) they make a substantial modification to a high-risk AI system that has already been placed on the market or has already been put into service in such a way that it remains a high-risk AI system pursuant to Article 6; (c) they modify the intended purpose of an AI system, including a general-purpose AI system, which has not been classified as high-risk and has already been placed on the market or put into service in such a way that the AI system concerned becomes a high-risk AI system in accordance with Article 6. 2.   Where the circumstances referred to in paragraph 1 occur, the provider that initially placed the AI system on the market or put it into service shall no longer be considered to be a provider of that specific AI system for the purposes of this Regulation. That initial provider shall closely cooperate with new providers and shall make available the necessary information and provide the reasonably expected technical access and other assistance that are required for the fulfilment…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-26",
    "article_no": "26",
    "title": "Obligations of deployers of high-risk AI systems",
    "snippet": "1.   Deployers of high-risk AI systems shall take appropriate technical and organisational measures to ensure they use such systems in accordance with the instructions for use accompanying the…",
    "full_text": "1.   Deployers of high-risk AI systems shall take appropriate technical and organisational measures to ensure they use such systems in accordance with the instructions for use accompanying the systems, pursuant to paragraphs 3 and 6. 2.   Deployers shall assign human oversight to natural persons who have the necessary competence, training and authority, as well as the necessary support. 3.   The obligations set out in paragraphs 1 and 2, are without prejudice to other deployer obligations under Union or national law and to the deployer’s freedom to organise its own resources and activities for the purpose of implementing the human oversight measures indicated by the provider. 4.   Without prejudice to paragraphs 1 and 2, to the extent the deployer exercises control over the input data, that deployer shall ensure that input data is relevant and sufficiently representative in view of the intended purpose of the high-risk AI system. 5.   Deployers shall monitor the operation of the high-risk AI system on the basis of the instructions for use and, where relevant, inform providers in accordance with Article 72. Where deployers have reason to consider that the use of the high-risk AI system in accordance with the instructions may result in that AI system presenting a risk within the meaning of Article 79(1), they shall, without undue delay, inform the provider or distributor and the relevant market surveillance authority, and shall suspend the use of that system. Where deployers…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-28",
    "article_no": "28",
    "title": "Notifying authorities",
    "snippet": "1.   Each Member State shall designate or establish at least one notifying authority responsible for setting up and carrying out the necessary procedures for the assessment, designation and…",
    "full_text": "1.   Each Member State shall designate or establish at least one notifying authority responsible for setting up and carrying out the necessary procedures for the assessment, designation and notification of conformity assessment bodies and for their monitoring. Those procedures shall be developed in cooperation between the notifying authorities of all Member States. 2.   Member States may decide that the assessment and monitoring referred to in paragraph 1 is to be carried out by a national accreditation body within the meaning of, and in accordance with, Regulation (EC) No 765/2008. 3.   Notifying authorities shall be established, organised and operated in such a way that no conflict of interest arises with conformity assessment bodies, and that the objectivity and impartiality of their activities are safeguarded. 4.   Notifying authorities shall be organised in such a way that decisions relating to the notification of conformity assessment bodies are taken by competent persons different from those who carried out the assessment of those bodies. 5.   Notifying authorities shall offer or provide neither any activities that conformity assessment bodies perform, nor any consultancy services on a commercial or competitive basis. 6.   Notifying authorities shall safeguard the confidentiality of the information that they obtain, in accordance with Article 78. 7.   Notifying authorities shall have an adequate number of competent personnel at their disposal for the proper…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-29",
    "article_no": "29",
    "title": "Application of a conformity assessment body for notification",
    "snippet": "1.   Conformity assessment bodies shall submit an application for notification to the notifying authority of the Member State in which they are established. 2.   The application for notification…",
    "full_text": "1.   Conformity assessment bodies shall submit an application for notification to the notifying authority of the Member State in which they are established. 2.   The application for notification shall be accompanied by a description of the conformity assessment activities, the conformity assessment module or modules and the types of AI systems for which the conformity assessment body claims to be competent, as well as by an accreditation certificate, where one exists, issued by a national accreditation body attesting that the conformity assessment body fulfils the requirements laid down in Article 31. Any valid document related to existing designations of the applicant notified body under any other Union harmonisation legislation shall be added. 3.   Where the conformity assessment body concerned cannot provide an accreditation certificate, it shall provide the notifying authority with all the documentary evidence necessary for the verification, recognition and regular monitoring of its compliance with the requirements laid down in Article 31. 4.   For notified bodies which are designated under any other Union harmonisation legislation, all documents and certificates linked to those designations may be used to support their designation procedure under this Regulation, as appropriate. The notified body shall update the documentation referred to in paragraphs 2 and 3 of this Article whenever relevant changes occur, in order to enable the authority responsible for notified…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-43",
    "article_no": "43",
    "title": "Conformity assessment",
    "snippet": "1.   For high-risk AI systems listed in point 1 of Annex III, where, in demonstrating the compliance of a high-risk AI system with the requirements set out in Section 2, the provider has applied…",
    "full_text": "1.   For high-risk AI systems listed in point 1 of Annex III, where, in demonstrating the compliance of a high-risk AI system with the requirements set out in Section 2, the provider has applied harmonised standards referred to in Article 40, or, where applicable, common specifications referred to in Article 41, the provider shall opt for one of the following conformity assessment procedures based on: (a) the internal control referred to in Annex VI; or (b) the assessment of the quality management system and the assessment of the technical documentation, with the involvement of a notified body, referred to in Annex VII. In demonstrating the compliance of a high-risk AI system with the requirements set out in Section 2, the provider shall follow the conformity assessment procedure set out in Annex VII where: (a) harmonised standards referred to in Article 40 do not exist, and common specifications referred to in Article 41 are not available; (b) the provider has not applied, or has applied only part of, the harmonised standard; (c) the common specifications referred to in point (a) exist, but the provider has not applied them; (d) one or more of the harmonised standards referred to in point (a) has been published with a restriction, and only on the part of the standard that was restricted. For the purposes of the conformity assessment procedure referred to in Annex VII, the provider may choose any of the notified bodies. However, where the high-risk AI system is intended to…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-49",
    "article_no": "49",
    "title": "Registration",
    "snippet": "1.   Before placing on the market or putting into service a high-risk AI system listed in Annex III, with the exception of high-risk AI systems referred to in point 2 of Annex III, the provider or,…",
    "full_text": "1.   Before placing on the market or putting into service a high-risk AI system listed in Annex III, with the exception of high-risk AI systems referred to in point 2 of Annex III, the provider or, where applicable, the authorised representative shall register themselves and their system in the EU database referred to in Article 71. 2.   Before placing on the market or putting into service an AI system for which the provider has concluded that it is not high-risk according to Article 6(3), that provider or, where applicable, the authorised representative shall register themselves and that system in the EU database referred to in Article 71. 3.   Before putting into service or using a high-risk AI system listed in Annex III, with the exception of high-risk AI systems listed in point 2 of Annex III, deployers that are public authorities, Union institutions, bodies, offices or agencies or persons acting on their behalf shall register themselves, select the system and register its use in the EU database referred to in Article 71. 4.   For high-risk AI systems referred to in points 1, 6 and 7 of Annex III, in the areas of law enforcement, migration, asylum and border control management, the registration referred to in paragraphs 1, 2 and 3 of this Article shall be in a secure non-public section of the EU database referred to in Article 71 and shall include only the following information, as applicable, referred to in: (a) Section A, points 1 to 10, of Annex VIII, with the…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-52",
    "article_no": "52",
    "title": "Procedure",
    "snippet": "1.   Where a general-purpose AI model meets the condition referred to in Article 51(1), point (a), the relevant provider shall notify the Commission without delay and in any event within two weeks…",
    "full_text": "1.   Where a general-purpose AI model meets the condition referred to in Article 51(1), point (a), the relevant provider shall notify the Commission without delay and in any event within two weeks after that requirement is met or it becomes known that it will be met. That notification shall include the information necessary to demonstrate that the relevant requirement has been met. If the Commission becomes aware of a general-purpose AI model presenting systemic risks of which it has not been notified, it may decide to designate it as a model with systemic risk. 2.   The provider of a general-purpose AI model that meets the condition referred to in Article 51(1), point (a), may present, with its notification, sufficiently substantiated arguments to demonstrate that, exceptionally, although it meets that requirement, the general-purpose AI model does not present, due to its specific characteristics, systemic risks and therefore should not be classified as a general-purpose AI model with systemic risk. 3.   Where the Commission concludes that the arguments submitted pursuant to paragraph 2 are not sufficiently substantiated and the relevant provider was not able to demonstrate that the general-purpose AI model does not present, due to its specific characteristics, systemic risks, it shall reject those arguments, and the general-purpose AI model shall be considered to be a general-purpose AI model with systemic risk. 4.   The Commission may designate a general-purpose AI model…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-56",
    "article_no": "56",
    "title": "Codes of practice",
    "snippet": "1.   The AI Office shall encourage and facilitate the drawing up of codes of practice at Union level in order to contribute to the proper application of this Regulation, taking into account…",
    "full_text": "1.   The AI Office shall encourage and facilitate the drawing up of codes of practice at Union level in order to contribute to the proper application of this Regulation, taking into account international approaches. 2.   The AI Office and the Board shall aim to ensure that the codes of practice cover at least the obligations provided for in Articles 53 and 55, including the following issues: (a) the means to ensure that the information referred to in Article 53(1), points (a) and (b), is kept up to date in light of market and technological developments; (b) the adequate level of detail for the summary about the content used for training; (c) the identification of the type and nature of the systemic risks at Union level, including their sources, where appropriate; (d) the measures, procedures and modalities for the assessment and management of the systemic risks at Union level, including the documentation thereof, which shall be proportionate to the risks, take into consideration their severity and probability and take into account the specific challenges of tackling those risks in light of the possible ways in which such risks may emerge and materialise along the AI value chain. 3.   The AI Office may invite all providers of general-purpose AI models, as well as relevant national competent authorities, to participate in the drawing-up of codes of practice. Civil society organisations, industry, academia and other relevant stakeholders, such as downstream providers and…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-72",
    "article_no": "72",
    "title": "Post-market monitoring by providers and post-market monitoring plan for high-risk AI systems",
    "snippet": "1.   Providers shall establish and document a post-market monitoring system in a manner that is proportionate to the nature of the AI technologies and the risks of the high-risk AI system. 2.   The…",
    "full_text": "1.   Providers shall establish and document a post-market monitoring system in a manner that is proportionate to the nature of the AI technologies and the risks of the high-risk AI system. 2.   The post-market monitoring system shall actively and systematically collect, document and analyse relevant data which may be provided by deployers or which may be collected through other sources on the performance of high-risk AI systems throughout their lifetime, and which allow the provider to evaluate the continuous compliance of AI systems with the requirements set out in Chapter III, Section 2. Where relevant, post-market monitoring shall include an analysis of the interaction with other AI systems. This obligation shall not cover sensitive operational data of deployers which are law-enforcement authorities. 3.   The post-market monitoring system shall be based on a post-market monitoring plan. The post-market monitoring plan shall be part of the technical documentation referred to in Annex IV. The Commission shall adopt an implementing act laying down detailed provisions establishing a template for the post-market monitoring plan and the list of elements to be included in the plan by 2 February 2026. That implementing act shall be adopted in accordance with the examination procedure referred to in Article 98(2). 4.   For high-risk AI systems covered by the Union harmonisation legislation listed in Section A of Annex I, where a post-market monitoring system and plan are already…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-73",
    "article_no": "73",
    "title": "Reporting of serious incidents",
    "snippet": "1.   Providers of high-risk AI systems placed on the Union market shall report any serious incident to the market surveillance authorities of the Member States where that incident occurred. 2.   The…",
    "full_text": "1.   Providers of high-risk AI systems placed on the Union market shall report any serious incident to the market surveillance authorities of the Member States where that incident occurred. 2.   The report referred to in paragraph 1 shall be made immediately after the provider has established a causal link between the AI system and the serious incident or the reasonable likelihood of such a link, and, in any event, not later than 15 days after the provider or, where applicable, the deployer, becomes aware of the serious incident. The period for the reporting referred to in the first subparagraph shall take account of the severity of the serious incident. 3.   Notwithstanding paragraph 2 of this Article, in the event of a widespread infringement or a serious incident as defined in Article 3, point (49)(b), the report referred to in paragraph 1 of this Article shall be provided immediately, and not later than two days after the provider or, where applicable, the deployer becomes aware of that incident. 4.   Notwithstanding paragraph 2, in the event of the death of a person, the report shall be provided immediately after the provider or the deployer has established, or as soon as it suspects, a causal relationship between the high-risk AI system and the serious incident, but not later than 10 days after the date on which the provider or, where applicable, the deployer becomes aware of the serious incident. 5.   Where necessary to ensure timely reporting, the provider or, where…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-99",
    "article_no": "99",
    "title": "Penalties",
    "snippet": "1.   In accordance with the terms and conditions laid down in this Regulation, Member States shall lay down the rules on penalties and other enforcement measures, which may also include warnings and…",
    "full_text": "1.   In accordance with the terms and conditions laid down in this Regulation, Member States shall lay down the rules on penalties and other enforcement measures, which may also include warnings and non-monetary measures, applicable to infringements of this Regulation by operators, and shall take all measures necessary to ensure that they are properly and effectively implemented, thereby taking into account the guidelines issued by the Commission pursuant to Article 96. The penalties provided for shall be effective, proportionate and dissuasive. They shall take into account the interests of SMEs, including start-ups, and their economic viability. 2.   The Member States shall, without delay and at the latest by the date of entry into application, notify the Commission of the rules on penalties and of other enforcement measures referred to in paragraph 1, and shall notify it, without delay, of any subsequent amendment to them. 3.   Non-compliance with the prohibition of the AI practices referred to in Article 5 shall be subject to administrative fines of up to EUR 35 000 000 or, if the offender is an undertaking, up to 7 % of its total worldwide annual turnover for the preceding financial year, whichever is higher. 4.   Non-compliance with any of the following provisions related to operators or notified bodies, other than those laid down in Articles 5, shall be subject to administrative fines of up to EUR 15 000 000 or, if the offender is an undertaking, up to 3 % of its total…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-100",
    "article_no": "100",
    "title": "Administrative fines on Union institutions, bodies, offices and agencies",
    "snippet": "1.   The European Data Protection Supervisor may impose administrative fines on Union institutions, bodies, offices and agencies falling within the scope of this Regulation. When deciding whether to…",
    "full_text": "1.   The European Data Protection Supervisor may impose administrative fines on Union institutions, bodies, offices and agencies falling within the scope of this Regulation. When deciding whether to impose an administrative fine and when deciding on the amount of the administrative fine in each individual case, all relevant circumstances of the specific situation shall be taken into account and due regard shall be given to the following: (a) the nature, gravity and duration of the infringement and of its consequences, taking into account the purpose of the AI system concerned, as well as, where appropriate, the number of affected persons and the level of damage suffered by them; (b) the degree of responsibility of the Union institution, body, office or agency, taking into account technical and organisational measures implemented by them; (c) any action taken by the Union institution, body, office or agency to mitigate the damage suffered by affected persons; (d) the degree of cooperation with the European Data Protection Supervisor in order to remedy the infringement and mitigate the possible adverse effects of the infringement, including compliance with any of the measures previously ordered by the European Data Protection Supervisor against the Union institution, body, office or agency concerned with regard to the same subject matter; (e) any similar previous infringements by the Union institution, body, office or agency; (f) the manner in which the infringement became…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Art-113",
    "article_no": "113",
    "title": "Entry into force and application",
    "snippet": "This Regulation shall enter into force on the twentieth day following that of its publication in the Official Journal of the European Union . It shall apply from 2 August 2026. However: (a) Chapters…",
    "full_text": "This Regulation shall enter into force on the twentieth day following that of its publication in the Official Journal of the European Union . It shall apply from 2 August 2026. However: (a) Chapters I and II shall apply from 2 February 2025; (b) Chapter III Section 4, Chapter V, Chapter VII and Chapter XII and Article 78 shall apply from 2 August 2025, with the exception of Article 101; (c) Article 6(1) and the corresponding obligations in this Regulation shall apply from 2 August 2027. This Regulation shall be binding in its entirety and directly applicable in all Member States. Done at Brussels, 13 June 2024.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Annex-II",
    "article_no": "Annex-II",
    "title": "Annex II — List of criminal offences referred to in Article 5(1), first subparagraph, point (h)(iii)",
    "snippet": "Criminal offences referred to in Article 5(1), first subparagraph, point (h)(iii): — terrorism, — trafficking in human beings, — sexual exploitation of children, and child pornography, — illicit…",
    "full_text": "Criminal offences referred to in Article 5(1), first subparagraph, point (h)(iii): — terrorism, — trafficking in human beings, — sexual exploitation of children, and child pornography, — illicit trafficking in narcotic drugs or psychotropic substances, — illicit trafficking in weapons, munitions or explosives, — murder, grievous bodily injury, — illicit trade in human organs or tissue, — illicit trafficking in nuclear or radioactive materials, — kidnapping, illegal restraint or hostage-taking, — crimes within the jurisdiction of the International Criminal Court, — unlawful seizure of aircraft or ships, — rape, — environmental crime, — organised or armed robbery, — sabotage, — participation in a criminal organisation involved in one or more of the offences listed above.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Annex-IV",
    "article_no": "Annex-IV",
    "title": "Annex IV — Technical documentation referred to in Article 11(1)",
    "snippet": "The technical documentation referred to in Article 11(1) shall contain at least the following information, as applicable to the relevant AI system: 1. A general description of the AI system…",
    "full_text": "The technical documentation referred to in Article 11(1) shall contain at least the following information, as applicable to the relevant AI system: 1. A general description of the AI system including: (a) its intended purpose, the name of the provider and the version of the system reflecting its relation to previous versions; (b) how the AI system interacts with, or can be used to interact with, hardware or software, including with other AI systems, that are not part of the AI system itself, where applicable; (c) the versions of relevant software or firmware, and any requirements related to version updates; (d) the description of all the forms in which the AI system is placed on the market or put into service, such as software packages embedded into hardware, downloads, or APIs; (e) the description of the hardware on which the AI system is intended to run; (f) where the AI system is a component of products, photographs or illustrations showing external features, the marking and internal layout of those products; (g) a basic description of the user-interface provided to the deployer; (h) instructions for use for the deployer, and a basic description of the user-interface provided to the deployer, where applicable; 2. A detailed description of the elements of the AI system and of the process for its development, including: (a) the methods and steps performed for the development of the AI system, including, where relevant, recourse to pre-trained systems or tools provided by…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Annex-VIII",
    "article_no": "Annex-VIII",
    "title": "Annex VIII — Information to be submitted upon the registration of high-risk AI systems in accordance with Article 49",
    "snippet": "The following information shall be provided and thereafter kept up to date with regard to high-risk AI systems to be registered in accordance with Article 49(1): 1. The name, address and contact…",
    "full_text": "The following information shall be provided and thereafter kept up to date with regard to high-risk AI systems to be registered in accordance with Article 49(1): 1. The name, address and contact details of the provider; 2. Where submission of information is carried out by another person on behalf of the provider, the name, address and contact details of that person; 3. The name, address and contact details of the authorised representative, where applicable; 4. The AI system trade name and any additional unambiguous reference allowing the identification and traceability of the AI system; 5. A description of the intended purpose of the AI system and of the components and functions supported through this AI system; 6. A basic and concise description of the information used by the system (data, inputs) and its operating logic; 7. The status of the AI system (on the market, or in service; no longer placed on the market/in service, recalled); 8. The type, number and expiry date of the certificate issued by the notified body and the name or identification number of that notified body, where applicable; 9. A scanned copy of the certificate referred to in point 8, where applicable; 10. Any Member States in which the AI system has been placed on the market, put into service or made available in the Union; 11. A copy of the EU declaration of conformity referred to in Article 47; 12. Electronic instructions for use; this information shall not be provided for high-risk AI systems in the…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-7",
    "article_no": "Recital-7",
    "title": "Recital 7",
    "snippet": "In order to ensure a consistent and high level of protection of public interests as regards health, safety and fundamental rights, common rules for high-risk AI systems should be established. Those…",
    "full_text": "In order to ensure a consistent and high level of protection of public interests as regards health, safety and fundamental rights, common rules for high-risk AI systems should be established. Those rules should be consistent with the Charter, non-discriminatory and in line with the Union’s international trade commitments. They should also take into account the European Declaration on Digital Rights and Principles for the Digital Decade and the Ethics guidelines for trustworthy AI of the High-Level Expert Group on Artificial Intelligence (AI HLEG).",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-27",
    "article_no": "Recital-27",
    "title": "Recital 27",
    "snippet": "While the risk-based approach is the basis for a proportionate and effective set of binding rules, it is important to recall the 2019 Ethics guidelines for trustworthy AI developed by the independent…",
    "full_text": "While the risk-based approach is the basis for a proportionate and effective set of binding rules, it is important to recall the 2019 Ethics guidelines for trustworthy AI developed by the independent AI HLEG appointed by the Commission. In those guidelines, the AI HLEG developed seven non-binding ethical principles for AI which are intended to help ensure that AI is trustworthy and ethically sound. The seven principles include human agency and oversight; technical robustness and safety; privacy and data governance; transparency; diversity, non-discrimination and fairness; societal and environmental well-being and accountability. Without prejudice to the legally binding requirements of this Regulation and any other applicable Union law, those guidelines contribute to the design of coherent, trustworthy and human-centric AI, in line with the Charter and with the values on which the Union is founded. According to the guidelines of the AI HLEG, human agency and oversight means that AI systems are developed and used as a tool that serves people, respects human dignity and personal autonomy, and that is functioning in a way that can be appropriately controlled and overseen by humans. Technical robustness and safety means that AI systems are developed and used in a way that allows robustness in the case of problems and resilience against attempts to alter the use or performance of the AI system so as to allow unlawful use by third parties, and minimise unintended harm. Privacy and…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-38",
    "article_no": "Recital-38",
    "title": "Recital 38",
    "snippet": "The use of AI systems for real-time remote biometric identification of natural persons in publicly accessible spaces for the purpose of law enforcement necessarily involves the processing of…",
    "full_text": "The use of AI systems for real-time remote biometric identification of natural persons in publicly accessible spaces for the purpose of law enforcement necessarily involves the processing of biometric data. The rules of this Regulation that prohibit, subject to certain exceptions, such use, which are based on Article 16 TFEU, should apply as lex specialis in respect of the rules on the processing of biometric data contained in Article 10 of Directive (EU) 2016/680, thus regulating such use and the processing of biometric data involved in an exhaustive manner. Therefore, such use and processing should be possible only in as far as it is compatible with the framework set by this Regulation, without there being scope, outside that framework, for the competent authorities, where they act for purpose of law enforcement, to use such systems and process such data in connection thereto on the grounds listed in Article 10 of Directive (EU) 2016/680. In that context, this Regulation is not intended to provide the legal basis for the processing of personal data under Article 8 of Directive (EU) 2016/680. However, the use of real-time remote biometric identification systems in publicly accessible spaces for purposes other than law enforcement, including by competent authorities, should not be covered by the specific framework regarding such use for the purpose of law enforcement set by this Regulation. Such use for purposes other than law enforcement should therefore not be subject to…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-65",
    "article_no": "Recital-65",
    "title": "Recital 65",
    "snippet": "The risk-management system should consist of a continuous, iterative process that is planned and run throughout the entire lifecycle of a high-risk AI system. That process should be aimed at…",
    "full_text": "The risk-management system should consist of a continuous, iterative process that is planned and run throughout the entire lifecycle of a high-risk AI system. That process should be aimed at identifying and mitigating the relevant risks of AI systems on health, safety and fundamental rights. The risk-management system should be regularly reviewed and updated to ensure its continuing effectiveness, as well as justification and documentation of any significant decisions and actions taken subject to this Regulation. This process should ensure that the provider identifies risks or adverse impacts and implements mitigation measures for the known and reasonably foreseeable risks of AI systems to the health, safety and fundamental rights in light of their intended purpose and reasonably foreseeable misuse, including the possible risks arising from the interaction between the AI system and the environment within which it operates. The risk-management system should adopt the most appropriate risk-management measures in light of the state of the art in AI. When identifying the most appropriate risk-management measures, the provider should document and explain the choices made and, when relevant, involve experts and external stakeholders. In identifying the reasonably foreseeable misuse of high-risk AI systems, the provider should cover uses of AI systems which, while not directly covered by the intended purpose and provided for in the instruction for use may nevertheless be reasonably…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-89",
    "article_no": "Recital-89",
    "title": "Recital 89",
    "snippet": "Third parties making accessible to the public tools, services, processes, or AI components other than general-purpose AI models, should not be mandated to comply with requirements targeting the…",
    "full_text": "Third parties making accessible to the public tools, services, processes, or AI components other than general-purpose AI models, should not be mandated to comply with requirements targeting the responsibilities along the AI value chain, in particular towards the provider that has used or integrated them, when those tools, services, processes, or AI components are made accessible under a free and open-source licence. Developers of free and open-source tools, services, processes, or AI components other than general-purpose AI models should be encouraged to implement widely adopted documentation practices, such as model cards and data sheets, as a way to accelerate information sharing along the AI value chain, allowing the promotion of trustworthy AI systems in the Union.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-96",
    "article_no": "Recital-96",
    "title": "Recital 96",
    "snippet": "In order to efficiently ensure that fundamental rights are protected, deployers of high-risk AI systems that are bodies governed by public law, or private entities providing public services and…",
    "full_text": "In order to efficiently ensure that fundamental rights are protected, deployers of high-risk AI systems that are bodies governed by public law, or private entities providing public services and deployers of certain high-risk AI systems listed in an annex to this Regulation, such as banking or insurance entities, should carry out a fundamental rights impact assessment prior to putting it into use. Services important for individuals that are of public nature may also be provided by private entities. Private entities providing such public services are linked to tasks in the public interest such as in the areas of education, healthcare, social services, housing, administration of justice. The aim of the fundamental rights impact assessment is for the deployer to identify the specific risks to the rights of individuals or groups of individuals likely to be affected, identify measures to be taken in the case of a materialisation of those risks. The impact assessment should be performed prior to deploying the high-risk AI system, and should be updated when the deployer considers that any of the relevant factors have changed. The impact assessment should identify the deployer’s relevant processes in which the high-risk AI system will be used in line with its intended purpose, and should include a description of the period of time and frequency in which the system is intended to be used as well as of specific categories of natural persons and groups who are likely to be affected in…",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-107",
    "article_no": "Recital-107",
    "title": "Recital 107",
    "snippet": "In order to increase transparency on the data that is used in the pre-training and training of general-purpose AI models, including text and data protected by copyright law, it is adequate that…",
    "full_text": "In order to increase transparency on the data that is used in the pre-training and training of general-purpose AI models, including text and data protected by copyright law, it is adequate that providers of such models draw up and make publicly available a sufficiently detailed summary of the content used for training the general-purpose AI model. While taking into due account the need to protect trade secrets and confidential business information, this summary should be generally comprehensive in its scope instead of technically detailed to facilitate parties with legitimate interests, including copyright holders, to exercise and enforce their rights under Union law, for example by listing the main data collections or sets that went into training the model, such as large private or public databases or data archives, and by providing a narrative explanation about other data sources used. It is appropriate for the AI Office to provide a template for the summary, which should be simple, effective, and allow the provider to provide the required summary in narrative form.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-Recital-138",
    "article_no": "Recital-138",
    "title": "Recital 138",
    "snippet": "AI is a rapidly developing family of technologies that requires regulatory oversight and a safe and controlled space for experimentation, while ensuring responsible innovation and integration of…",
    "full_text": "AI is a rapidly developing family of technologies that requires regulatory oversight and a safe and controlled space for experimentation, while ensuring responsible innovation and integration of appropriate safeguards and risk mitigation measures. To ensure a legal framework that promotes innovation, is future-proof and resilient to disruption, Member States should ensure that their national competent authorities establish at least one AI regulatory sandbox at national level to facilitate the development and testing of innovative AI systems under strict regulatory oversight before these systems are placed on the market or otherwise put into service. Member States could also fulfil this obligation through participating in already existing regulatory sandboxes or establishing jointly a sandbox with one or more Member States’ competent authorities, insofar as this participation provides equivalent level of national coverage for the participating Member States. AI regulatory sandboxes could be established in physical, digital or hybrid form and may accommodate physical as well as digital products. Establishing authorities should also ensure that the AI regulatory sandboxes have the adequate resources for their functioning, including financial and human resources.",
    "source_type": "legislation",
    "source_label": "EU AI Act 2024/1689 (EUR-Lex consolidated text)",
    "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    "relevance_score": null
  },
  {
    "code": "R-FI-traficom-supervisor",
    "article_no": "FI-supervisor",
    "title": "Traficom — Finland's national competent authority under the EU AI Act",
    "snippet": "Traficom is Finland's lead national authority for the EU AI Act. The AI Act entered into force on 1 August 2024, and Member States must designate national competent authorities for market surveillance and notifying bodies.",
    "full_text": "Traficom (Finnish Transport and Communications Agency) is positioned as Finland's lead national competent authority for the implementation of Regulation 2024/1689 (EU AI Act). Traficom hosts AI Act information pages and a public customer service desk covering the Data, AI and Data Governance Regulations. Under Article 70 of the AI Act, each Member State designates one or more national competent authorities responsible for market surveillance. Sector-specific Finnish supervisors (e.g. Finanssivalvonta for financial-sector AI, Valvira for health-sector AI) cooperate where their existing mandates intersect with AI-system use.",
    "source_type": "national",
    "source_label": "Traficom (Finnish Transport and Communications Agency) — AI Act information pages",
    "url": "https://www.traficom.fi/en/ai-regulation",
    "relevance_score": null
  },
  {
    "code": "R-FI-sandbox",
    "article_no": "FI-sandbox",
    "title": "Finnish AI regulatory sandbox (AI Act Art. 57)",
    "snippet": "The EU AI Act entered into force on 1 August 2024. It introduces binding rules for the development and use of artificial intelligence across the EU. One of the Act's key practical tools is the AI regulatory sandbox, a controlled experimentation and testing environment for AI innovation under the supervision of competent authorities.",
    "full_text": "Under Article 57 of the AI Act, each Member State must establish at least one AI regulatory sandbox at national level. The Finnish sandbox is administered through Traficom as a controlled experimentation environment where providers and prospective providers can develop, train, validate, and test innovative AI systems before placing them on the market or putting them into service. The sandbox enables experimentation with AI technologies while maintaining supervision by competent authorities. Participating providers benefit from regulatory guidance, reduced administrative penalties for good-faith engagement, and structured feedback on compliance gaps before formal conformity assessment.",
    "source_type": "national",
    "source_label": "Traficom (Finnish Transport and Communications Agency) — AI Act information pages",
    "url": "https://www.traficom.fi/en/ai-regulation/ai-regulatory-sandboxes",
    "relevance_score": null
  },
  {
    "code": "R-FI-customer-service",
    "article_no": "FI-cs",
    "title": "Traficom customer service for Data, AI and Data Governance Regulations",
    "snippet": "Traficom provides a dedicated customer service for questions concerning the Data Regulation, AI Act, and Data Governance Regulation. Finnish-based providers and deployers can request guidance on classification, oversight obligations, and conformity-assessment routes.",
    "full_text": "Traficom operates a customer-facing helpdesk covering the suite of EU regulations on data and AI: the Data Regulation, the AI Act (Regulation 2024/1689), and the Data Governance Regulation. Finnish-based providers and deployers are invited to seek guidance on whether their use case falls into Annex III high-risk categories, what oversight and transparency obligations apply, and how the Finnish sandbox application process works. This customer-service channel is the recommended first contact for organisations attempting an AI-Act first-pass assessment in Finland.",
    "source_type": "national",
    "source_label": "Traficom (Finnish Transport and Communications Agency) — AI Act information pages",
    "url": "https://www.traficom.fi/en/ai-regulation",
    "relevance_score": null
  }
];
